package model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * SapOrgUnit definition.
 * 
 * This file was generated by Ignite Web Console (01/31/2019, 12:31)
 **/
public class SapOrgUnit implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for createdDate. */
    private Timestamp createdDate;

    /** Value for createdUserId. */
    private String createdUserId;

    /** Value for changedDate. */
    private Timestamp changedDate;

    /** Value for changedUserId. */
    private String changedUserId;

    /** Value for logicallyDeleted. */
    private String logicallyDeleted;

    /** Value for recordVersion. */
    private BigDecimal recordVersion;

    /** Value for name. */
    private String name;

    /** Value for shortName. */
    private String shortName;

    /** Value for department. */
    private String department;

    /** Value for businessArea. */
    private String businessArea;

    /** Value for filename. */
    private String filename;

    /** Value for fileversion. */
    private String fileversion;

    /** Empty constructor. **/
    public SapOrgUnit() {
        // No-op.
    }

    /** Full constructor. **/
    public SapOrgUnit(Timestamp createdDate,
        String createdUserId,
        Timestamp changedDate,
        String changedUserId,
        String logicallyDeleted,
        BigDecimal recordVersion,
        String name,
        String shortName,
        String department,
        String businessArea,
        String filename,
        String fileversion) {
        this.createdDate = createdDate;
        this.createdUserId = createdUserId;
        this.changedDate = changedDate;
        this.changedUserId = changedUserId;
        this.logicallyDeleted = logicallyDeleted;
        this.recordVersion = recordVersion;
        this.name = name;
        this.shortName = shortName;
        this.department = department;
        this.businessArea = businessArea;
        this.filename = filename;
        this.fileversion = fileversion;
    }

    /**
     * Gets createdDate
     * 
     * @return Value for createdDate.
     **/
    public Timestamp getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets createdDate
     * 
     * @param createdDate New value for createdDate.
     **/
    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Gets createdUserId
     * 
     * @return Value for createdUserId.
     **/
    public String getCreatedUserId() {
        return createdUserId;
    }

    /**
     * Sets createdUserId
     * 
     * @param createdUserId New value for createdUserId.
     **/
    public void setCreatedUserId(String createdUserId) {
        this.createdUserId = createdUserId;
    }

    /**
     * Gets changedDate
     * 
     * @return Value for changedDate.
     **/
    public Timestamp getChangedDate() {
        return changedDate;
    }

    /**
     * Sets changedDate
     * 
     * @param changedDate New value for changedDate.
     **/
    public void setChangedDate(Timestamp changedDate) {
        this.changedDate = changedDate;
    }

    /**
     * Gets changedUserId
     * 
     * @return Value for changedUserId.
     **/
    public String getChangedUserId() {
        return changedUserId;
    }

    /**
     * Sets changedUserId
     * 
     * @param changedUserId New value for changedUserId.
     **/
    public void setChangedUserId(String changedUserId) {
        this.changedUserId = changedUserId;
    }

    /**
     * Gets logicallyDeleted
     * 
     * @return Value for logicallyDeleted.
     **/
    public String getLogicallyDeleted() {
        return logicallyDeleted;
    }

    /**
     * Sets logicallyDeleted
     * 
     * @param logicallyDeleted New value for logicallyDeleted.
     **/
    public void setLogicallyDeleted(String logicallyDeleted) {
        this.logicallyDeleted = logicallyDeleted;
    }

    /**
     * Gets recordVersion
     * 
     * @return Value for recordVersion.
     **/
    public BigDecimal getRecordVersion() {
        return recordVersion;
    }

    /**
     * Sets recordVersion
     * 
     * @param recordVersion New value for recordVersion.
     **/
    public void setRecordVersion(BigDecimal recordVersion) {
        this.recordVersion = recordVersion;
    }

    /**
     * Gets name
     * 
     * @return Value for name.
     **/
    public String getName() {
        return name;
    }

    /**
     * Sets name
     * 
     * @param name New value for name.
     **/
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets shortName
     * 
     * @return Value for shortName.
     **/
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets shortName
     * 
     * @param shortName New value for shortName.
     **/
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * Gets department
     * 
     * @return Value for department.
     **/
    public String getDepartment() {
        return department;
    }

    /**
     * Sets department
     * 
     * @param department New value for department.
     **/
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * Gets businessArea
     * 
     * @return Value for businessArea.
     **/
    public String getBusinessArea() {
        return businessArea;
    }

    /**
     * Sets businessArea
     * 
     * @param businessArea New value for businessArea.
     **/
    public void setBusinessArea(String businessArea) {
        this.businessArea = businessArea;
    }

    /**
     * Gets filename
     * 
     * @return Value for filename.
     **/
    public String getFilename() {
        return filename;
    }

    /**
     * Sets filename
     * 
     * @param filename New value for filename.
     **/
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Gets fileversion
     * 
     * @return Value for fileversion.
     **/
    public String getFileversion() {
        return fileversion;
    }

    /**
     * Sets fileversion
     * 
     * @param fileversion New value for fileversion.
     **/
    public void setFileversion(String fileversion) {
        this.fileversion = fileversion;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof SapOrgUnit))
            return false;
        
        SapOrgUnit that = (SapOrgUnit)o;

        if (createdDate != null ? !createdDate.equals(that.createdDate) : that.createdDate != null)
            return false;
        

        if (createdUserId != null ? !createdUserId.equals(that.createdUserId) : that.createdUserId != null)
            return false;
        

        if (changedDate != null ? !changedDate.equals(that.changedDate) : that.changedDate != null)
            return false;
        

        if (changedUserId != null ? !changedUserId.equals(that.changedUserId) : that.changedUserId != null)
            return false;
        

        if (logicallyDeleted != null ? !logicallyDeleted.equals(that.logicallyDeleted) : that.logicallyDeleted != null)
            return false;
        

        if (recordVersion != null ? !recordVersion.equals(that.recordVersion) : that.recordVersion != null)
            return false;
        

        if (name != null ? !name.equals(that.name) : that.name != null)
            return false;
        

        if (shortName != null ? !shortName.equals(that.shortName) : that.shortName != null)
            return false;
        

        if (department != null ? !department.equals(that.department) : that.department != null)
            return false;
        

        if (businessArea != null ? !businessArea.equals(that.businessArea) : that.businessArea != null)
            return false;
        

        if (filename != null ? !filename.equals(that.filename) : that.filename != null)
            return false;
        

        if (fileversion != null ? !fileversion.equals(that.fileversion) : that.fileversion != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = createdDate != null ? createdDate.hashCode() : 0;

        res = 31 * res + (createdUserId != null ? createdUserId.hashCode() : 0);

        res = 31 * res + (changedDate != null ? changedDate.hashCode() : 0);

        res = 31 * res + (changedUserId != null ? changedUserId.hashCode() : 0);

        res = 31 * res + (logicallyDeleted != null ? logicallyDeleted.hashCode() : 0);

        res = 31 * res + (recordVersion != null ? recordVersion.hashCode() : 0);

        res = 31 * res + (name != null ? name.hashCode() : 0);

        res = 31 * res + (shortName != null ? shortName.hashCode() : 0);

        res = 31 * res + (department != null ? department.hashCode() : 0);

        res = 31 * res + (businessArea != null ? businessArea.hashCode() : 0);

        res = 31 * res + (filename != null ? filename.hashCode() : 0);

        res = 31 * res + (fileversion != null ? fileversion.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "SapOrgUnit [" + 
            "createdDate=" + createdDate + ", " + 
            "createdUserId=" + createdUserId + ", " + 
            "changedDate=" + changedDate + ", " + 
            "changedUserId=" + changedUserId + ", " + 
            "logicallyDeleted=" + logicallyDeleted + ", " + 
            "recordVersion=" + recordVersion + ", " + 
            "name=" + name + ", " + 
            "shortName=" + shortName + ", " + 
            "department=" + department + ", " + 
            "businessArea=" + businessArea + ", " + 
            "filename=" + filename + ", " + 
            "fileversion=" + fileversion +
        "]";
    }
}