package load;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (01/31/2019, 12:31) **/
public class LoadCaches {
    /**
     * <p>
     * Utility to load caches from database.
     * <p>
     * How to use:
     * <ul>
     *     <li>Start cluster.</li>
     *     <li>Start this utility and wait while load complete.</li>
     * </ul>
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        try (Ignite ignite = Ignition.start("sap-ignite-client.xml")) {
            System.out.println(">>> Loading caches...");

            System.out.println(">>> Loading cache: FeedSapEmployeeCache");
            ignite.cache("FeedSapEmployeeCache").loadCache(null);

            System.out.println(">>> Loading cache: SapEmployeeGroupCache");
            ignite.cache("SapEmployeeGroupCache").loadCache(null);

            System.out.println(">>> Loading cache: SapEmployeeSubGroupCache");
            ignite.cache("SapEmployeeSubGroupCache").loadCache(null);

            System.out.println(">>> Loading cache: SapEntityCache");
            ignite.cache("SapEntityCache").loadCache(null);

            System.out.println(">>> Loading cache: SapLocationCache");
            ignite.cache("SapLocationCache").loadCache(null);

            System.out.println(">>> Loading cache: SapOrgDepartmentCache");
            ignite.cache("SapOrgDepartmentCache").loadCache(null);

            System.out.println(">>> Loading cache: SapOrgUnitCache");
            ignite.cache("SapOrgUnitCache").loadCache(null);

            System.out.println(">>> Loading cache: SapStaffCache");
            ignite.cache("SapStaffCache").loadCache(null);

            System.out.println(">>> All caches loaded!");
        }
    }
}