package startup;

import org.apache.ignite.Ignite;
import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (01/31/2019, 12:31) **/
public class ServerNodeSpringStartup {
	
	private static Ignite ignite;
	
	private static final String[] CACHES = {
			"FeedSapEmployeeCache", "SapEmployeeGroupCache", "SapEmployeeSubGroupCache", "SapEntityCache", 
			"SapLocationCache", "SapOrgDepartmentCache", "SapOrgUnitCache", "SapStaffCache"
	};
    /**
     * Start up node with specified configuration.
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
    	ignite = Ignition.start("sap-ignite-server.xml");
    }
    
    public void loadCaches() {
        System.out.println(">>> Loading caches...");
        
        for(String cacheName : CACHES) 
        	ignite.cache(cacheName).loadCache(null);

        System.out.println(">>> All caches loaded!");
    }
}