package config;

import java.io.InputStream;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Properties;
import javax.cache.configuration.Factory;
import javax.sql.DataSource;
import oracle.jdbc.pool.OracleDataSource;
import org.apache.ignite.cache.CacheAtomicityMode;
import org.apache.ignite.cache.CacheMode;
import org.apache.ignite.cache.QueryEntity;
import org.apache.ignite.cache.QueryIndex;
import org.apache.ignite.cache.QueryIndexType;
import org.apache.ignite.cache.store.jdbc.CacheJdbcPojoStoreFactory;
import org.apache.ignite.cache.store.jdbc.JdbcType;
import org.apache.ignite.cache.store.jdbc.JdbcTypeField;
import org.apache.ignite.cache.store.jdbc.dialect.OracleDialect;
import org.apache.ignite.configuration.CacheConfiguration;
import org.apache.ignite.configuration.DataRegionConfiguration;
import org.apache.ignite.configuration.DataStorageConfiguration;
import org.apache.ignite.configuration.IgniteConfiguration;
import org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi;
import org.apache.ignite.spi.discovery.tcp.ipfinder.vm.TcpDiscoveryVmIpFinder;

/** This file was generated by Ignite Web Console (01/31/2019, 12:31) **/
public class ClientConfigurationFactory {
    /** Secret properties loading. **/
    private static final Properties props = new Properties();

    static {
        try (InputStream in = IgniteConfiguration.class.getClassLoader().getResourceAsStream("secret.properties")) {
            props.load(in);
        }
        catch (Exception ignored) {
            // No-op.
        }
    }

    /** Helper class for datasource creation. **/
    public static class DataSources {
        public static final OracleDataSource INSTANCE_dsOracle_Orcl = createdsOracle_Orcl();

        private static OracleDataSource createdsOracle_Orcl() {
            try {
                OracleDataSource dsOracle_Orcl = new OracleDataSource();

                dsOracle_Orcl.setURL(props.getProperty("dsOracle_Orcl.jdbc.url"));
                dsOracle_Orcl.setUser(props.getProperty("dsOracle_Orcl.jdbc.username"));
                dsOracle_Orcl.setPassword(props.getProperty("dsOracle_Orcl.jdbc.password"));

                return dsOracle_Orcl;
            }
            catch (SQLException ex) {
                throw new Error(ex);
            }
        }
    }

    /**
     * Configure grid.
     * 
     * @return Ignite configuration.
     * @throws Exception If failed to construct Ignite configuration instance.
     **/
    public static IgniteConfiguration createConfiguration() throws Exception {
        IgniteConfiguration cfg = new IgniteConfiguration();

        cfg.setClientMode(true);
        cfg.setIgniteInstanceName("sap-ignite");

        TcpDiscoverySpi discovery = new TcpDiscoverySpi();

        TcpDiscoveryVmIpFinder ipFinder = new TcpDiscoveryVmIpFinder();

        ipFinder.setAddresses(Arrays.asList("127.0.0.1:47500..47510"));

        discovery.setIpFinder(ipFinder);

        cfg.setDiscoverySpi(discovery);

        DataStorageConfiguration dataStorageCfg = new DataStorageConfiguration();

        dataStorageCfg.setPageSize(8192);

        DataRegionConfiguration dataRegionCfg = new DataRegionConfiguration();

        dataRegionCfg.setPersistenceEnabled(true);

        dataStorageCfg.setDefaultDataRegionConfiguration(dataRegionCfg);

        dataStorageCfg.setWalHistorySize(50);

        cfg.setDataStorageConfiguration(dataStorageCfg);

        cfg.setCacheConfiguration(
            cacheFeedSapEmployeeCache(),
            cacheSapEmployeeGroupCache(),
            cacheSapEmployeeSubGroupCache(),
            cacheSapEntityCache(),
            cacheSapLocationCache(),
            cacheSapOrgDepartmentCache(),
            cacheSapOrgUnitCache(),
            cacheSapStaffCache()
        );

        return cfg;
    }

    /**
     * Create configuration for cache "FeedSapEmployeeCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheFeedSapEmployeeCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("FeedSapEmployeeCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeFeedSapEmployee(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.lang.String");
        qryEntity.setValueType("model.FeedSapEmployee");
        qryEntity.setTableName("FEED_SAP_EMPLOYEE");
        qryEntity.setKeyFieldName("personalid");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("personalid");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("sevendigitstaffid", "java.lang.Long");
        fields.put("forename", "java.lang.String");
        fields.put("surname", "java.lang.String");
        fields.put("sapcostcentrecompany", "java.lang.String");
        fields.put("startdt", "java.lang.String");
        fields.put("enddt", "java.lang.String");
        fields.put("corporatetitle", "java.lang.String");
        fields.put("globallevel", "java.lang.String");
        fields.put("stafftype", "java.lang.String");
        fields.put("staffsubtype", "java.lang.String");
        fields.put("staffstatus", "java.lang.String");
        fields.put("staffclass", "java.lang.String");
        fields.put("globalstaffid", "java.lang.Long");
        fields.put("taxnumber", "java.lang.String");
        fields.put("orgunit", "java.lang.String");
        fields.put("orgunitabbv", "java.lang.String");
        fields.put("orgunitdesc", "java.lang.String");
        fields.put("dept", "java.lang.String");
        fields.put("deptabbv", "java.lang.String");
        fields.put("deptdesc", "java.lang.String");
        fields.put("buildingdesc", "java.lang.String");
        fields.put("countrydesc", "java.lang.String");
        fields.put("firstname", "java.lang.String");
        fields.put("jobkey", "java.lang.String");
        fields.put("linemanagerid", "java.lang.String");
        fields.put("previouslastname", "java.lang.String");
        fields.put("gender", "java.lang.String");
        fields.put("lastdayworked", "java.lang.String");
        fields.put("emailaddr", "java.lang.String");
        fields.put("previouscostcentre", "java.lang.String");
        fields.put("lastdaypaid", "java.lang.String");
        fields.put("dateofbirth", "java.lang.String");
        fields.put("nationalitycode", "java.lang.String");
        fields.put("maternitydatefrom", "java.lang.String");
        fields.put("maternitydateto", "java.lang.String");
        fields.put("absence", "java.lang.String");
        fields.put("entitycode", "java.lang.String");
        fields.put("entitytext", "java.lang.String");
        fields.put("busarea1", "java.lang.String");
        fields.put("busareaabbr1", "java.lang.String");
        fields.put("busareadesc1", "java.lang.String");
        fields.put("busarea2", "java.lang.String");
        fields.put("busareaabbr2", "java.lang.String");
        fields.put("busareadesc2", "java.lang.String");
        fields.put("busarea3", "java.lang.String");
        fields.put("busareaabbr3", "java.lang.String");
        fields.put("busareadesc3", "java.lang.String");
        fields.put("busarea4", "java.lang.String");
        fields.put("busareaabbr4", "java.lang.String");
        fields.put("busareadesc4", "java.lang.String");
        fields.put("leavingcode", "java.lang.String");
        fields.put("graduatestartdate", "java.lang.String");
        fields.put("localhirerehire", "java.lang.String");
        fields.put("localsupervisor", "java.lang.String");
        fields.put("linemanagerbrid", "java.lang.String");
        fields.put("brid", "java.lang.String");
        fields.put("personnelarea", "java.lang.String");
        fields.put("personnelareadesc", "java.lang.String");
        fields.put("busarea5", "java.lang.String");
        fields.put("busareaabbr5", "java.lang.String");
        fields.put("busareadesc5", "java.lang.String");
        fields.put("subfunction", "java.lang.String");
        fields.put("subfunctiondesc", "java.lang.String");
        fields.put("function", "java.lang.String");
        fields.put("functiondesc", "java.lang.String");
        fields.put("sapcostcentretext", "java.lang.String");
        fields.put("companycode", "java.lang.String");
        fields.put("companycodetxt", "java.lang.String");
        fields.put("operationalstatusind", "java.lang.String");
        fields.put("citizencard", "java.lang.String");
        fields.put("evetelephoneno", "java.lang.String");
        fields.put("identificationcard", "java.lang.String");
        fields.put("pannumber", "java.lang.String");
        fields.put("nationalidcardno", "java.lang.String");
        fields.put("labourcardnumberid", "java.lang.String");
        fields.put("personalmobceltelephoneno", "java.lang.String");
        fields.put("employmentpass", "java.lang.String");
        fields.put("singaporeblue", "java.lang.String");
        fields.put("passport", "java.lang.String");
        fields.put("hongkongidentityno", "java.lang.String");
        fields.put("uniquenationalid", "java.lang.String");
        fields.put("singaporepink", "java.lang.String");
        fields.put("visaworkpermitreftier2", "java.lang.String");
        fields.put("busarea6", "java.lang.String");
        fields.put("busareaabbr6", "java.lang.String");
        fields.put("busareadesc6", "java.lang.String");
        fields.put("busarea7", "java.lang.String");
        fields.put("busareaabbr7", "java.lang.String");
        fields.put("busareadesc7", "java.lang.String");
        fields.put("busarea8", "java.lang.String");
        fields.put("busareaabbr8", "java.lang.String");
        fields.put("busareadesc8", "java.lang.String");
        fields.put("busarea9", "java.lang.String");
        fields.put("busareaabbr9", "java.lang.String");
        fields.put("busareadesc9", "java.lang.String");
        fields.put("busarea10", "java.lang.String");
        fields.put("busareaabbr10", "java.lang.String");
        fields.put("busareadesc10", "java.lang.String");
        fields.put("opnonopstatusreason", "java.lang.String");
        fields.put("opnonopstartdate", "java.lang.String");
        fields.put("opnonopenddate", "java.lang.String");
        fields.put("personalid", "java.lang.String");

        qryEntity.setFields(fields);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeFeedSapEmployee".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeFeedSapEmployee(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(String.class);
        type.setValueType("model.FeedSapEmployee");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("FEED_SAP_EMPLOYEE");

        type.setKeyFields(new JdbcTypeField(Types.VARCHAR, "PERSONALID", String.class, "personalid"));

        type.setValueFields(
            new JdbcTypeField(Types.BIGINT, "SEVENDIGITSTAFFID", Long.class, "sevendigitstaffid"),
            new JdbcTypeField(Types.VARCHAR, "FORENAME", String.class, "forename"),
            new JdbcTypeField(Types.VARCHAR, "SURNAME", String.class, "surname"),
            new JdbcTypeField(Types.VARCHAR, "SAPCOSTCENTRECOMPANY", String.class, "sapcostcentrecompany"),
            new JdbcTypeField(Types.VARCHAR, "STARTDT", String.class, "startdt"),
            new JdbcTypeField(Types.VARCHAR, "ENDDT", String.class, "enddt"),
            new JdbcTypeField(Types.VARCHAR, "CORPORATETITLE", String.class, "corporatetitle"),
            new JdbcTypeField(Types.VARCHAR, "GLOBALLEVEL", String.class, "globallevel"),
            new JdbcTypeField(Types.VARCHAR, "STAFFTYPE", String.class, "stafftype"),
            new JdbcTypeField(Types.VARCHAR, "STAFFSUBTYPE", String.class, "staffsubtype"),
            new JdbcTypeField(Types.VARCHAR, "STAFFSTATUS", String.class, "staffstatus"),
            new JdbcTypeField(Types.VARCHAR, "STAFFCLASS", String.class, "staffclass"),
            new JdbcTypeField(Types.BIGINT, "GLOBALSTAFFID", Long.class, "globalstaffid"),
            new JdbcTypeField(Types.VARCHAR, "TAXNUMBER", String.class, "taxnumber"),
            new JdbcTypeField(Types.VARCHAR, "ORGUNIT", String.class, "orgunit"),
            new JdbcTypeField(Types.VARCHAR, "ORGUNITABBV", String.class, "orgunitabbv"),
            new JdbcTypeField(Types.VARCHAR, "ORGUNITDESC", String.class, "orgunitdesc"),
            new JdbcTypeField(Types.VARCHAR, "DEPT", String.class, "dept"),
            new JdbcTypeField(Types.VARCHAR, "DEPTABBV", String.class, "deptabbv"),
            new JdbcTypeField(Types.VARCHAR, "DEPTDESC", String.class, "deptdesc"),
            new JdbcTypeField(Types.VARCHAR, "BUILDINGDESC", String.class, "buildingdesc"),
            new JdbcTypeField(Types.VARCHAR, "COUNTRYDESC", String.class, "countrydesc"),
            new JdbcTypeField(Types.VARCHAR, "FIRSTNAME", String.class, "firstname"),
            new JdbcTypeField(Types.VARCHAR, "JOBKEY", String.class, "jobkey"),
            new JdbcTypeField(Types.VARCHAR, "LINEMANAGERID", String.class, "linemanagerid"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUSLASTNAME", String.class, "previouslastname"),
            new JdbcTypeField(Types.CHAR, "GENDER", String.class, "gender"),
            new JdbcTypeField(Types.VARCHAR, "LASTDAYWORKED", String.class, "lastdayworked"),
            new JdbcTypeField(Types.VARCHAR, "EMAILADDR", String.class, "emailaddr"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUSCOSTCENTRE", String.class, "previouscostcentre"),
            new JdbcTypeField(Types.VARCHAR, "LASTDAYPAID", String.class, "lastdaypaid"),
            new JdbcTypeField(Types.VARCHAR, "DATEOFBIRTH", String.class, "dateofbirth"),
            new JdbcTypeField(Types.VARCHAR, "NATIONALITYCODE", String.class, "nationalitycode"),
            new JdbcTypeField(Types.VARCHAR, "MATERNITYDATEFROM", String.class, "maternitydatefrom"),
            new JdbcTypeField(Types.VARCHAR, "MATERNITYDATETO", String.class, "maternitydateto"),
            new JdbcTypeField(Types.VARCHAR, "ABSENCE", String.class, "absence"),
            new JdbcTypeField(Types.VARCHAR, "ENTITYCODE", String.class, "entitycode"),
            new JdbcTypeField(Types.VARCHAR, "ENTITYTEXT", String.class, "entitytext"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA1", String.class, "busarea1"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR1", String.class, "busareaabbr1"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC1", String.class, "busareadesc1"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA2", String.class, "busarea2"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR2", String.class, "busareaabbr2"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC2", String.class, "busareadesc2"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA3", String.class, "busarea3"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR3", String.class, "busareaabbr3"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC3", String.class, "busareadesc3"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA4", String.class, "busarea4"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR4", String.class, "busareaabbr4"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC4", String.class, "busareadesc4"),
            new JdbcTypeField(Types.VARCHAR, "LEAVINGCODE", String.class, "leavingcode"),
            new JdbcTypeField(Types.VARCHAR, "GRADUATESTARTDATE", String.class, "graduatestartdate"),
            new JdbcTypeField(Types.VARCHAR, "LOCALHIREREHIRE", String.class, "localhirerehire"),
            new JdbcTypeField(Types.VARCHAR, "LOCALSUPERVISOR", String.class, "localsupervisor"),
            new JdbcTypeField(Types.VARCHAR, "LINEMANAGERBRID", String.class, "linemanagerbrid"),
            new JdbcTypeField(Types.VARCHAR, "BRID", String.class, "brid"),
            new JdbcTypeField(Types.VARCHAR, "PERSONNELAREA", String.class, "personnelarea"),
            new JdbcTypeField(Types.VARCHAR, "PERSONNELAREADESC", String.class, "personnelareadesc"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA5", String.class, "busarea5"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR5", String.class, "busareaabbr5"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC5", String.class, "busareadesc5"),
            new JdbcTypeField(Types.VARCHAR, "SUBFUNCTION", String.class, "subfunction"),
            new JdbcTypeField(Types.VARCHAR, "SUBFUNCTIONDESC", String.class, "subfunctiondesc"),
            new JdbcTypeField(Types.VARCHAR, "FUNCTION", String.class, "function"),
            new JdbcTypeField(Types.VARCHAR, "FUNCTIONDESC", String.class, "functiondesc"),
            new JdbcTypeField(Types.VARCHAR, "SAPCOSTCENTRETEXT", String.class, "sapcostcentretext"),
            new JdbcTypeField(Types.VARCHAR, "COMPANYCODE", String.class, "companycode"),
            new JdbcTypeField(Types.VARCHAR, "COMPANYCODETXT", String.class, "companycodetxt"),
            new JdbcTypeField(Types.VARCHAR, "OPERATIONALSTATUSIND", String.class, "operationalstatusind"),
            new JdbcTypeField(Types.VARCHAR, "CITIZENCARD", String.class, "citizencard"),
            new JdbcTypeField(Types.VARCHAR, "EVETELEPHONENO", String.class, "evetelephoneno"),
            new JdbcTypeField(Types.VARCHAR, "IDENTIFICATIONCARD", String.class, "identificationcard"),
            new JdbcTypeField(Types.VARCHAR, "PANNUMBER", String.class, "pannumber"),
            new JdbcTypeField(Types.VARCHAR, "NATIONALIDCARDNO", String.class, "nationalidcardno"),
            new JdbcTypeField(Types.VARCHAR, "LABOURCARDNUMBERID", String.class, "labourcardnumberid"),
            new JdbcTypeField(Types.VARCHAR, "PERSONALMOBCELTELEPHONENO", String.class, "personalmobceltelephoneno"),
            new JdbcTypeField(Types.VARCHAR, "EMPLOYMENTPASS", String.class, "employmentpass"),
            new JdbcTypeField(Types.VARCHAR, "SINGAPOREBLUE", String.class, "singaporeblue"),
            new JdbcTypeField(Types.VARCHAR, "PASSPORT", String.class, "passport"),
            new JdbcTypeField(Types.VARCHAR, "HONGKONGIDENTITYNO", String.class, "hongkongidentityno"),
            new JdbcTypeField(Types.VARCHAR, "UNIQUENATIONALID", String.class, "uniquenationalid"),
            new JdbcTypeField(Types.VARCHAR, "SINGAPOREPINK", String.class, "singaporepink"),
            new JdbcTypeField(Types.VARCHAR, "VISAWORKPERMITREFTIER2", String.class, "visaworkpermitreftier2"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA6", String.class, "busarea6"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR6", String.class, "busareaabbr6"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC6", String.class, "busareadesc6"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA7", String.class, "busarea7"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR7", String.class, "busareaabbr7"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC7", String.class, "busareadesc7"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA8", String.class, "busarea8"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR8", String.class, "busareaabbr8"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC8", String.class, "busareadesc8"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA9", String.class, "busarea9"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR9", String.class, "busareaabbr9"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC9", String.class, "busareadesc9"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREA10", String.class, "busarea10"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREAABBR10", String.class, "busareaabbr10"),
            new JdbcTypeField(Types.VARCHAR, "BUSAREADESC10", String.class, "busareadesc10"),
            new JdbcTypeField(Types.VARCHAR, "OPNONOPSTATUSREASON", String.class, "opnonopstatusreason"),
            new JdbcTypeField(Types.VARCHAR, "OPNONOPSTARTDATE", String.class, "opnonopstartdate"),
            new JdbcTypeField(Types.VARCHAR, "OPNONOPENDDATE", String.class, "opnonopenddate")
        );

        return type;
    }

    /**
     * Create configuration for cache "SapEmployeeGroupCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheSapEmployeeGroupCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("SapEmployeeGroupCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);
        ccfg.setCopyOnRead(true);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeSapEmployeeGroup(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.lang.String");
        qryEntity.setValueType("model.SapEmployeeGroup");
        qryEntity.setTableName("SAP_EMPLOYEE_GROUP");
        qryEntity.setKeyFieldName("code");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("code");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("name", "java.lang.String");
        fields.put("logicallyDeleted", "java.lang.String");
        fields.put("recordVersion", "java.math.BigDecimal");
        fields.put("createdUserId", "java.lang.String");
        fields.put("createdDate", "java.sql.Timestamp");
        fields.put("changedUserId", "java.lang.String");
        fields.put("changedDate", "java.sql.Timestamp");
        fields.put("filename", "java.lang.String");
        fields.put("fileversion", "java.lang.String");
        fields.put("code", "java.lang.String");

        qryEntity.setFields(fields);

        HashMap<String, String> aliases = new HashMap<>();

        aliases.put("logicallyDeleted", "LOGICALLY_DELETED");
        aliases.put("recordVersion", "RECORD_VERSION");
        aliases.put("createdUserId", "CREATED_USER_ID");
        aliases.put("createdDate", "CREATED_DATE");
        aliases.put("changedUserId", "CHANGED_USER_ID");
        aliases.put("changedDate", "CHANGED_DATE");

        qryEntity.setAliases(aliases);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeSapEmployeeGroup".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeSapEmployeeGroup(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(String.class);
        type.setValueType("model.SapEmployeeGroup");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("SAP_EMPLOYEE_GROUP");

        type.setKeyFields(new JdbcTypeField(Types.VARCHAR, "CODE", String.class, "code"));

        type.setValueFields(
            new JdbcTypeField(Types.VARCHAR, "NAME", String.class, "name"),
            new JdbcTypeField(Types.CHAR, "LOGICALLY_DELETED", String.class, "logicallyDeleted"),
            new JdbcTypeField(Types.NUMERIC, "RECORD_VERSION", BigDecimal.class, "recordVersion"),
            new JdbcTypeField(Types.VARCHAR, "CREATED_USER_ID", String.class, "createdUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CREATED_DATE", Timestamp.class, "createdDate"),
            new JdbcTypeField(Types.VARCHAR, "CHANGED_USER_ID", String.class, "changedUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CHANGED_DATE", Timestamp.class, "changedDate"),
            new JdbcTypeField(Types.VARCHAR, "FILENAME", String.class, "filename"),
            new JdbcTypeField(Types.VARCHAR, "FILEVERSION", String.class, "fileversion")
        );

        return type;
    }

    /**
     * Create configuration for cache "SapEmployeeSubGroupCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheSapEmployeeSubGroupCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("SapEmployeeSubGroupCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeSapEmployeeSubGroup(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.lang.String");
        qryEntity.setValueType("model.SapEmployeeSubGroup");
        qryEntity.setTableName("SAP_EMPLOYEE_SUB_GROUP");
        qryEntity.setKeyFieldName("code");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("code");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("name", "java.lang.String");
        fields.put("logicallyDeleted", "java.lang.String");
        fields.put("recordVersion", "java.math.BigDecimal");
        fields.put("createdUserId", "java.lang.String");
        fields.put("createdDate", "java.sql.Timestamp");
        fields.put("changedUserId", "java.lang.String");
        fields.put("changedDate", "java.sql.Timestamp");
        fields.put("filename", "java.lang.String");
        fields.put("fileversion", "java.lang.String");
        fields.put("code", "java.lang.String");

        qryEntity.setFields(fields);

        HashMap<String, String> aliases = new HashMap<>();

        aliases.put("logicallyDeleted", "LOGICALLY_DELETED");
        aliases.put("recordVersion", "RECORD_VERSION");
        aliases.put("createdUserId", "CREATED_USER_ID");
        aliases.put("createdDate", "CREATED_DATE");
        aliases.put("changedUserId", "CHANGED_USER_ID");
        aliases.put("changedDate", "CHANGED_DATE");

        qryEntity.setAliases(aliases);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeSapEmployeeSubGroup".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeSapEmployeeSubGroup(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(String.class);
        type.setValueType("model.SapEmployeeSubGroup");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("SAP_EMPLOYEE_SUB_GROUP");

        type.setKeyFields(new JdbcTypeField(Types.VARCHAR, "CODE", String.class, "code"));

        type.setValueFields(
            new JdbcTypeField(Types.VARCHAR, "NAME", String.class, "name"),
            new JdbcTypeField(Types.CHAR, "LOGICALLY_DELETED", String.class, "logicallyDeleted"),
            new JdbcTypeField(Types.NUMERIC, "RECORD_VERSION", BigDecimal.class, "recordVersion"),
            new JdbcTypeField(Types.VARCHAR, "CREATED_USER_ID", String.class, "createdUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CREATED_DATE", Timestamp.class, "createdDate"),
            new JdbcTypeField(Types.VARCHAR, "CHANGED_USER_ID", String.class, "changedUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CHANGED_DATE", Timestamp.class, "changedDate"),
            new JdbcTypeField(Types.VARCHAR, "FILENAME", String.class, "filename"),
            new JdbcTypeField(Types.VARCHAR, "FILEVERSION", String.class, "fileversion")
        );

        return type;
    }

    /**
     * Create configuration for cache "SapEntityCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheSapEntityCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("SapEntityCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeSapEntity(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.lang.String");
        qryEntity.setValueType("model.SapEntity");
        qryEntity.setTableName("SAP_ENTITY");
        qryEntity.setKeyFieldName("code");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("code");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("createdDate", "java.sql.Timestamp");
        fields.put("createdUserId", "java.lang.String");
        fields.put("changedDate", "java.sql.Timestamp");
        fields.put("changedUserId", "java.lang.String");
        fields.put("logicallyDeleted", "java.lang.String");
        fields.put("recordVersion", "java.math.BigDecimal");
        fields.put("name", "java.lang.String");
        fields.put("filename", "java.lang.String");
        fields.put("fileversion", "java.lang.String");
        fields.put("code", "java.lang.String");

        qryEntity.setFields(fields);

        HashMap<String, String> aliases = new HashMap<>();

        aliases.put("createdDate", "CREATED_DATE");
        aliases.put("createdUserId", "CREATED_USER_ID");
        aliases.put("changedDate", "CHANGED_DATE");
        aliases.put("changedUserId", "CHANGED_USER_ID");
        aliases.put("logicallyDeleted", "LOGICALLY_DELETED");
        aliases.put("recordVersion", "RECORD_VERSION");

        qryEntity.setAliases(aliases);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeSapEntity".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeSapEntity(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(String.class);
        type.setValueType("model.SapEntity");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("SAP_ENTITY");

        type.setKeyFields(new JdbcTypeField(Types.VARCHAR, "CODE", String.class, "code"));

        type.setValueFields(
            new JdbcTypeField(Types.TIMESTAMP, "CREATED_DATE", Timestamp.class, "createdDate"),
            new JdbcTypeField(Types.VARCHAR, "CREATED_USER_ID", String.class, "createdUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CHANGED_DATE", Timestamp.class, "changedDate"),
            new JdbcTypeField(Types.VARCHAR, "CHANGED_USER_ID", String.class, "changedUserId"),
            new JdbcTypeField(Types.CHAR, "LOGICALLY_DELETED", String.class, "logicallyDeleted"),
            new JdbcTypeField(Types.NUMERIC, "RECORD_VERSION", BigDecimal.class, "recordVersion"),
            new JdbcTypeField(Types.VARCHAR, "NAME", String.class, "name"),
            new JdbcTypeField(Types.VARCHAR, "FILENAME", String.class, "filename"),
            new JdbcTypeField(Types.VARCHAR, "FILEVERSION", String.class, "fileversion")
        );

        return type;
    }

    /**
     * Create configuration for cache "SapLocationCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheSapLocationCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("SapLocationCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeSapLocation(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.math.BigDecimal");
        qryEntity.setValueType("model.SapLocation");
        qryEntity.setTableName("SAP_LOCATION");
        qryEntity.setKeyFieldName("id");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("id");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("createdDate", "java.sql.Timestamp");
        fields.put("createdUserId", "java.lang.String");
        fields.put("changedDate", "java.sql.Timestamp");
        fields.put("changedUserId", "java.lang.String");
        fields.put("logicallyDeleted", "java.lang.String");
        fields.put("recordVersion", "java.math.BigDecimal");
        fields.put("name", "java.lang.String");
        fields.put("office", "java.lang.String");
        fields.put("filename", "java.lang.String");
        fields.put("fileversion", "java.lang.String");
        fields.put("id", "java.math.BigDecimal");

        qryEntity.setFields(fields);

        HashMap<String, String> aliases = new HashMap<>();

        aliases.put("createdDate", "CREATED_DATE");
        aliases.put("createdUserId", "CREATED_USER_ID");
        aliases.put("changedDate", "CHANGED_DATE");
        aliases.put("changedUserId", "CHANGED_USER_ID");
        aliases.put("logicallyDeleted", "LOGICALLY_DELETED");
        aliases.put("recordVersion", "RECORD_VERSION");

        qryEntity.setAliases(aliases);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeSapLocation".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeSapLocation(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(BigDecimal.class);
        type.setValueType("model.SapLocation");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("SAP_LOCATION");

        type.setKeyFields(new JdbcTypeField(Types.NUMERIC, "ID", BigDecimal.class, "id"));

        type.setValueFields(
            new JdbcTypeField(Types.TIMESTAMP, "CREATED_DATE", Timestamp.class, "createdDate"),
            new JdbcTypeField(Types.VARCHAR, "CREATED_USER_ID", String.class, "createdUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CHANGED_DATE", Timestamp.class, "changedDate"),
            new JdbcTypeField(Types.VARCHAR, "CHANGED_USER_ID", String.class, "changedUserId"),
            new JdbcTypeField(Types.CHAR, "LOGICALLY_DELETED", String.class, "logicallyDeleted"),
            new JdbcTypeField(Types.NUMERIC, "RECORD_VERSION", BigDecimal.class, "recordVersion"),
            new JdbcTypeField(Types.VARCHAR, "NAME", String.class, "name"),
            new JdbcTypeField(Types.VARCHAR, "OFFICE", String.class, "office"),
            new JdbcTypeField(Types.VARCHAR, "FILENAME", String.class, "filename"),
            new JdbcTypeField(Types.VARCHAR, "FILEVERSION", String.class, "fileversion")
        );

        return type;
    }

    /**
     * Create configuration for cache "SapOrgDepartmentCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheSapOrgDepartmentCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("SapOrgDepartmentCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeSapOrgDepartment(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.lang.String");
        qryEntity.setValueType("model.SapOrgDepartment");
        qryEntity.setTableName("SAP_ORG_DEPARTMENT");
        qryEntity.setKeyFieldName("code");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("code");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("createdDate", "java.sql.Timestamp");
        fields.put("createdUserId", "java.lang.String");
        fields.put("changedDate", "java.sql.Timestamp");
        fields.put("changedUserId", "java.lang.String");
        fields.put("logicallyDeleted", "java.lang.String");
        fields.put("recordVersion", "java.math.BigDecimal");
        fields.put("name", "java.lang.String");
        fields.put("shortName", "java.lang.String");
        fields.put("filename", "java.lang.String");
        fields.put("fileversion", "java.lang.String");
        fields.put("code", "java.lang.String");

        qryEntity.setFields(fields);

        HashMap<String, String> aliases = new HashMap<>();

        aliases.put("createdDate", "CREATED_DATE");
        aliases.put("createdUserId", "CREATED_USER_ID");
        aliases.put("changedDate", "CHANGED_DATE");
        aliases.put("changedUserId", "CHANGED_USER_ID");
        aliases.put("logicallyDeleted", "LOGICALLY_DELETED");
        aliases.put("recordVersion", "RECORD_VERSION");
        aliases.put("shortName", "SHORT_NAME");

        qryEntity.setAliases(aliases);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeSapOrgDepartment".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeSapOrgDepartment(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(String.class);
        type.setValueType("model.SapOrgDepartment");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("SAP_ORG_DEPARTMENT");

        type.setKeyFields(new JdbcTypeField(Types.VARCHAR, "CODE", String.class, "code"));

        type.setValueFields(
            new JdbcTypeField(Types.TIMESTAMP, "CREATED_DATE", Timestamp.class, "createdDate"),
            new JdbcTypeField(Types.VARCHAR, "CREATED_USER_ID", String.class, "createdUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CHANGED_DATE", Timestamp.class, "changedDate"),
            new JdbcTypeField(Types.VARCHAR, "CHANGED_USER_ID", String.class, "changedUserId"),
            new JdbcTypeField(Types.CHAR, "LOGICALLY_DELETED", String.class, "logicallyDeleted"),
            new JdbcTypeField(Types.NUMERIC, "RECORD_VERSION", BigDecimal.class, "recordVersion"),
            new JdbcTypeField(Types.VARCHAR, "NAME", String.class, "name"),
            new JdbcTypeField(Types.VARCHAR, "SHORT_NAME", String.class, "shortName"),
            new JdbcTypeField(Types.VARCHAR, "FILENAME", String.class, "filename"),
            new JdbcTypeField(Types.VARCHAR, "FILEVERSION", String.class, "fileversion")
        );

        return type;
    }

    /**
     * Create configuration for cache "SapOrgUnitCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheSapOrgUnitCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("SapOrgUnitCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeSapOrgUnit(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.lang.String");
        qryEntity.setValueType("model.SapOrgUnit");
        qryEntity.setTableName("SAP_ORG_UNIT");
        qryEntity.setKeyFieldName("code");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("code");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("createdDate", "java.sql.Timestamp");
        fields.put("createdUserId", "java.lang.String");
        fields.put("changedDate", "java.sql.Timestamp");
        fields.put("changedUserId", "java.lang.String");
        fields.put("logicallyDeleted", "java.lang.String");
        fields.put("recordVersion", "java.math.BigDecimal");
        fields.put("name", "java.lang.String");
        fields.put("shortName", "java.lang.String");
        fields.put("department", "java.lang.String");
        fields.put("businessArea", "java.lang.String");
        fields.put("filename", "java.lang.String");
        fields.put("fileversion", "java.lang.String");
        fields.put("code", "java.lang.String");

        qryEntity.setFields(fields);

        HashMap<String, String> aliases = new HashMap<>();

        aliases.put("createdDate", "CREATED_DATE");
        aliases.put("createdUserId", "CREATED_USER_ID");
        aliases.put("changedDate", "CHANGED_DATE");
        aliases.put("changedUserId", "CHANGED_USER_ID");
        aliases.put("logicallyDeleted", "LOGICALLY_DELETED");
        aliases.put("recordVersion", "RECORD_VERSION");
        aliases.put("shortName", "SHORT_NAME");
        aliases.put("businessArea", "BUSINESS_AREA");

        qryEntity.setAliases(aliases);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeSapOrgUnit".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeSapOrgUnit(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(String.class);
        type.setValueType("model.SapOrgUnit");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("SAP_ORG_UNIT");

        type.setKeyFields(new JdbcTypeField(Types.VARCHAR, "CODE", String.class, "code"));

        type.setValueFields(
            new JdbcTypeField(Types.TIMESTAMP, "CREATED_DATE", Timestamp.class, "createdDate"),
            new JdbcTypeField(Types.VARCHAR, "CREATED_USER_ID", String.class, "createdUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CHANGED_DATE", Timestamp.class, "changedDate"),
            new JdbcTypeField(Types.VARCHAR, "CHANGED_USER_ID", String.class, "changedUserId"),
            new JdbcTypeField(Types.CHAR, "LOGICALLY_DELETED", String.class, "logicallyDeleted"),
            new JdbcTypeField(Types.NUMERIC, "RECORD_VERSION", BigDecimal.class, "recordVersion"),
            new JdbcTypeField(Types.VARCHAR, "NAME", String.class, "name"),
            new JdbcTypeField(Types.VARCHAR, "SHORT_NAME", String.class, "shortName"),
            new JdbcTypeField(Types.VARCHAR, "DEPARTMENT", String.class, "department"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA", String.class, "businessArea"),
            new JdbcTypeField(Types.VARCHAR, "FILENAME", String.class, "filename"),
            new JdbcTypeField(Types.VARCHAR, "FILEVERSION", String.class, "fileversion")
        );

        return type;
    }

    /**
     * Create configuration for cache "SapStaffCache".
     * 
     * @return Configured cache.
     * @throws Exception if failed to create cache configuration.
     **/
    public static CacheConfiguration cacheSapStaffCache() throws Exception {
        CacheConfiguration ccfg = new CacheConfiguration();

        ccfg.setName("SapStaffCache");
        ccfg.setCacheMode(CacheMode.PARTITIONED);
        ccfg.setAtomicityMode(CacheAtomicityMode.ATOMIC);

        CacheJdbcPojoStoreFactory cacheStoreFactory = new CacheJdbcPojoStoreFactory();

        cacheStoreFactory.setDataSourceFactory(new Factory<DataSource>() {
            /** {@inheritDoc} **/
            @Override public DataSource create() {
                return DataSources.INSTANCE_dsOracle_Orcl;
            };
        });

        cacheStoreFactory.setDialect(new OracleDialect());

        cacheStoreFactory.setTypes(jdbcTypeSapStaff(ccfg.getName()));

        ccfg.setCacheStoreFactory(cacheStoreFactory);

        ccfg.setReadThrough(true);
        ccfg.setWriteThrough(true);

        ArrayList<QueryEntity> qryEntities = new ArrayList<>();

        QueryEntity qryEntity = new QueryEntity();

        qryEntity.setKeyType("java.lang.Long");
        qryEntity.setValueType("model.SapStaff");
        qryEntity.setTableName("SAP_STAFF");
        qryEntity.setKeyFieldName("cdsStaffId");

        HashSet<String> keyFields = new HashSet<>();

        keyFields.add("cdsStaffId");

        qryEntity.setKeyFields(keyFields);

        LinkedHashMap<String, String> fields = new LinkedHashMap<>();

        fields.put("globalStaffId", "java.lang.Long");
        fields.put("globalStaffIdOld", "java.lang.Long");
        fields.put("windowsRealm", "java.lang.String");
        fields.put("windowsUsername", "java.lang.String");
        fields.put("staffStatus", "java.lang.String");
        fields.put("staffType", "java.lang.String");
        fields.put("corporateTitle", "java.lang.String");
        fields.put("title", "java.lang.String");
        fields.put("firstname", "java.lang.String");
        fields.put("surname", "java.lang.String");
        fields.put("forenames", "java.lang.String");
        fields.put("gender", "java.lang.String");
        fields.put("nationalityCode", "java.lang.String");
        fields.put("previousSurname", "java.lang.String");
        fields.put("addressLine1", "java.lang.String");
        fields.put("addressLine2", "java.lang.String");
        fields.put("addressChangeDate", "java.sql.Timestamp");
        fields.put("district", "java.lang.String");
        fields.put("city", "java.lang.String");
        fields.put("county", "java.lang.String");
        fields.put("country", "java.lang.String");
        fields.put("postcode", "java.lang.String");
        fields.put("emailAddress", "java.lang.String");
        fields.put("gtdEmailAddress", "java.lang.String");
        fields.put("staffHierarchy", "java.lang.Long");
        fields.put("startDate", "java.sql.Timestamp");
        fields.put("endDate", "java.sql.Timestamp");
        fields.put("leaver", "java.lang.String");
        fields.put("lastWorkedDate", "java.sql.Timestamp");
        fields.put("lastPaidDate", "java.sql.Timestamp");
        fields.put("originalStartDate", "java.sql.Timestamp");
        fields.put("terminationReason", "java.lang.String");
        fields.put("outOfOffice", "java.lang.String");
        fields.put("outOfOfficeReason", "java.lang.String");
        fields.put("outOfOfficeReturnDate", "java.sql.Timestamp");
        fields.put("orgUnit", "java.lang.String");
        fields.put("previousOrgUnit", "java.lang.String");
        fields.put("orgDepartment", "java.lang.String");
        fields.put("previousOrgDepartment", "java.lang.String");
        fields.put("costCentre", "java.lang.String");
        fields.put("previousCostCentre", "java.lang.String");
        fields.put("location", "java.math.BigDecimal");
        fields.put("prevLocation", "java.math.BigDecimal");
        fields.put("locationChangeDate", "java.sql.Timestamp");
        fields.put("floor", "java.lang.String");
        fields.put("deskNumber", "java.lang.String");
        fields.put("officeNormalBuildingId", "java.lang.String");
        fields.put("absent", "java.lang.String");
        fields.put("entity", "java.lang.String");
        fields.put("socialSecurityNumber", "java.lang.String");
        fields.put("dateOfBirth", "java.sql.Timestamp");
        fields.put("jobTitle", "java.lang.String");
        fields.put("jobRole", "java.lang.String");
        fields.put("extensionNumber", "java.lang.String");
        fields.put("globalDialNumber", "java.lang.String");
        fields.put("internationalNumber", "java.lang.String");
        fields.put("homePhone", "java.lang.String");
        fields.put("ldapUsername", "java.lang.String");
        fields.put("maternityEndDate", "java.sql.Timestamp");
        fields.put("maternityStartDate", "java.sql.Timestamp");
        fields.put("businessArea1", "java.lang.String");
        fields.put("businessArea2", "java.lang.String");
        fields.put("businessArea3", "java.lang.String");
        fields.put("businessArea4", "java.lang.String");
        fields.put("logicallyDeleted", "java.lang.String");
        fields.put("recordVersion", "java.math.BigDecimal");
        fields.put("createdUserId", "java.lang.String");
        fields.put("createdDate", "java.sql.Timestamp");
        fields.put("changedUserId", "java.lang.String");
        fields.put("changedDate", "java.sql.Timestamp");
        fields.put("employeeGroup", "java.lang.String");
        fields.put("employeeSubGroup", "java.lang.String");
        fields.put("nationalInsuranceNumber", "java.lang.String");
        fields.put("nationalRegistrationIdCard", "java.lang.String");
        fields.put("taxNumberOther", "java.lang.String");
        fields.put("previousEntity", "java.lang.String");
        fields.put("entityChangeDate", "java.sql.Timestamp");
        fields.put("orgDepartmentChangeDate", "java.sql.Timestamp");
        fields.put("orgUnitChangeDate", "java.sql.Timestamp");
        fields.put("costCentreChangeDate", "java.sql.Timestamp");
        fields.put("businessArea", "java.lang.String");
        fields.put("previousBusinessArea", "java.lang.String");
        fields.put("businessAreaChangeDate", "java.sql.Timestamp");
        fields.put("personnelSubArea", "java.lang.String");
        fields.put("payrollArea", "java.lang.String");
        fields.put("graduateStartDate", "java.sql.Timestamp");
        fields.put("previousBusinessArea1", "java.lang.String");
        fields.put("businessArea1ChangeDate", "java.sql.Timestamp");
        fields.put("previousBusinessArea2", "java.lang.String");
        fields.put("businessArea2ChangeDate", "java.sql.Timestamp");
        fields.put("previousBusinessArea3", "java.lang.String");
        fields.put("businessArea3ChangeDate", "java.sql.Timestamp");
        fields.put("previousBusinessArea4", "java.lang.String");
        fields.put("businessArea4ChangeDate", "java.sql.Timestamp");
        fields.put("lineManagerId", "java.lang.Long");
        fields.put("personnelArea", "java.lang.String");
        fields.put("lineManagerCdsStaffId", "java.lang.Long");
        fields.put("brid", "java.lang.String");
        fields.put("localSupervisorCdsStaffId", "java.lang.Long");
        fields.put("personnelAreaDesc", "java.lang.String");
        fields.put("businessArea5", "java.lang.String");
        fields.put("businessArea5ChangeDate", "java.sql.Timestamp");
        fields.put("previousBusinessArea5", "java.lang.String");
        fields.put("subFunction", "java.lang.String");
        fields.put("function", "java.lang.String");
        fields.put("companyCode", "java.lang.String");
        fields.put("previousAddressLine1", "java.lang.String");
        fields.put("addressLine1ChangeDate", "java.sql.Timestamp");
        fields.put("previousAddressLine2", "java.lang.String");
        fields.put("addressLine2ChangeDate", "java.sql.Timestamp");
        fields.put("previousDateOfBirth", "java.sql.Timestamp");
        fields.put("dateOfBirthChangeDate", "java.sql.Timestamp");
        fields.put("previousEmailAddress", "java.lang.String");
        fields.put("emailAddressChangeDate", "java.sql.Timestamp");
        fields.put("previousFirstname", "java.lang.String");
        fields.put("firstnameChangeDate", "java.sql.Timestamp");
        fields.put("previousForenames", "java.lang.String");
        fields.put("forenamesChangeDate", "java.sql.Timestamp");
        fields.put("previousGender", "java.lang.String");
        fields.put("genderChangeDate", "java.sql.Timestamp");
        fields.put("previousJobTitle", "java.lang.String");
        fields.put("jobTitleChangeDate", "java.sql.Timestamp");
        fields.put("previousNationalityCode", "java.lang.String");
        fields.put("nationalityCodeChangeDate", "java.sql.Timestamp");
        fields.put("previousPostcode", "java.lang.String");
        fields.put("postcodeChangeDate", "java.sql.Timestamp");
        fields.put("previousHomePhone", "java.lang.String");
        fields.put("homePhoneChangeDate", "java.sql.Timestamp");
        fields.put("previousGtdEmailAddress", "java.lang.String");
        fields.put("gtdEmailAddressChangeDate", "java.sql.Timestamp");
        fields.put("previousJobRole", "java.lang.String");
        fields.put("jobRoleChangeDate", "java.sql.Timestamp");
        fields.put("surnameChangeDate", "java.sql.Timestamp");
        fields.put("previousTermReason", "java.lang.String");
        fields.put("termReasonChangeDate", "java.sql.Timestamp");
        fields.put("previousLastPaidDate", "java.sql.Timestamp");
        fields.put("lastPaidChangeDate", "java.sql.Timestamp");
        fields.put("previousLastWorkedDate", "java.sql.Timestamp");
        fields.put("lastWorkedChangeDate", "java.sql.Timestamp");
        fields.put("previousStartDate", "java.sql.Timestamp");
        fields.put("startChangeDate", "java.sql.Timestamp");
        fields.put("officeMobile", "java.lang.String");
        fields.put("operationalStatusInd", "java.lang.String");
        fields.put("citizenCard", "java.lang.String");
        fields.put("eveningTelNo", "java.lang.String");
        fields.put("idCard", "java.lang.String");
        fields.put("panNo", "java.lang.String");
        fields.put("nationalIdCardNo", "java.lang.String");
        fields.put("labourCardNoId", "java.lang.String");
        fields.put("persMobCellTelNo", "java.lang.String");
        fields.put("employmentPass", "java.lang.String");
        fields.put("singaporeBlue", "java.lang.String");
        fields.put("passportNo", "java.lang.String");
        fields.put("hongkongIdNo", "java.lang.String");
        fields.put("personalId", "java.lang.String");
        fields.put("uniqueNationalId", "java.lang.String");
        fields.put("singaporePink", "java.lang.String");
        fields.put("visaWorkPermitRefTier2", "java.lang.String");
        fields.put("prevCorpTitle", "java.lang.String");
        fields.put("corpTitleChangeDate", "java.sql.Timestamp");
        fields.put("previousCompanyCode", "java.lang.String");
        fields.put("companyCodeChangeDate", "java.sql.Timestamp");
        fields.put("businessArea6", "java.lang.String");
        fields.put("previousBusinessArea6", "java.lang.String");
        fields.put("businessArea6ChangeDate", "java.sql.Timestamp");
        fields.put("businessArea7", "java.lang.String");
        fields.put("previousBusinessArea7", "java.lang.String");
        fields.put("businessArea7ChangeDate", "java.sql.Timestamp");
        fields.put("businessArea8", "java.lang.String");
        fields.put("previousBusinessArea8", "java.lang.String");
        fields.put("businessArea8ChangeDate", "java.sql.Timestamp");
        fields.put("businessArea9", "java.lang.String");
        fields.put("previousBusinessArea9", "java.lang.String");
        fields.put("businessArea9ChangeDate", "java.sql.Timestamp");
        fields.put("businessArea10", "java.lang.String");
        fields.put("previousBusinessArea10", "java.lang.String");
        fields.put("businessArea10ChangeDate", "java.sql.Timestamp");
        fields.put("prevLineManagerId", "java.lang.Long");
        fields.put("lineManagerIdChangeDate", "java.sql.Timestamp");
        fields.put("prevFunction", "java.lang.String");
        fields.put("functionChangeDate", "java.sql.Timestamp");
        fields.put("prevSubFunction", "java.lang.String");
        fields.put("subFunctionChangeDate", "java.sql.Timestamp");
        fields.put("oprStatusIndChangeDate", "java.sql.Timestamp");
        fields.put("opNonOpStatusReason", "java.lang.String");
        fields.put("opNonOpStartDate", "java.sql.Date");
        fields.put("opNonOpEndDate", "java.sql.Date");
        fields.put("overallRecordChangedDate", "java.sql.Timestamp");
        fields.put("cdsStaffId", "java.lang.Long");

        qryEntity.setFields(fields);

        HashMap<String, String> aliases = new HashMap<>();

        aliases.put("globalStaffId", "GLOBAL_STAFF_ID");
        aliases.put("globalStaffIdOld", "GLOBAL_STAFF_ID_OLD");
        aliases.put("windowsRealm", "WINDOWS_REALM");
        aliases.put("windowsUsername", "WINDOWS_USERNAME");
        aliases.put("staffStatus", "STAFF_STATUS");
        aliases.put("staffType", "STAFF_TYPE");
        aliases.put("corporateTitle", "CORPORATE_TITLE");
        aliases.put("nationalityCode", "NATIONALITY_CODE");
        aliases.put("previousSurname", "PREVIOUS_SURNAME");
        aliases.put("addressLine1", "ADDRESS_LINE1");
        aliases.put("addressLine2", "ADDRESS_LINE2");
        aliases.put("addressChangeDate", "ADDRESS_CHANGE_DATE");
        aliases.put("emailAddress", "EMAIL_ADDRESS");
        aliases.put("gtdEmailAddress", "GTD_EMAIL_ADDRESS");
        aliases.put("staffHierarchy", "STAFF_HIERARCHY");
        aliases.put("startDate", "START_DATE");
        aliases.put("endDate", "END_DATE");
        aliases.put("lastWorkedDate", "LAST_WORKED_DATE");
        aliases.put("lastPaidDate", "LAST_PAID_DATE");
        aliases.put("originalStartDate", "ORIGINAL_START_DATE");
        aliases.put("terminationReason", "TERMINATION_REASON");
        aliases.put("outOfOffice", "OUT_OF_OFFICE");
        aliases.put("outOfOfficeReason", "OUT_OF_OFFICE_REASON");
        aliases.put("outOfOfficeReturnDate", "OUT_OF_OFFICE_RETURN_DATE");
        aliases.put("orgUnit", "ORG_UNIT");
        aliases.put("previousOrgUnit", "PREVIOUS_ORG_UNIT");
        aliases.put("orgDepartment", "ORG_DEPARTMENT");
        aliases.put("previousOrgDepartment", "PREVIOUS_ORG_DEPARTMENT");
        aliases.put("costCentre", "COST_CENTRE");
        aliases.put("previousCostCentre", "PREVIOUS_COST_CENTRE");
        aliases.put("prevLocation", "PREV_LOCATION");
        aliases.put("locationChangeDate", "LOCATION_CHANGE_DATE");
        aliases.put("deskNumber", "DESK_NUMBER");
        aliases.put("officeNormalBuildingId", "OFFICE_NORMAL_BUILDING_ID");
        aliases.put("socialSecurityNumber", "SOCIAL_SECURITY_NUMBER");
        aliases.put("dateOfBirth", "DATE_OF_BIRTH");
        aliases.put("jobTitle", "JOB_TITLE");
        aliases.put("jobRole", "JOB_ROLE");
        aliases.put("extensionNumber", "EXTENSION_NUMBER");
        aliases.put("globalDialNumber", "GLOBAL_DIAL_NUMBER");
        aliases.put("internationalNumber", "INTERNATIONAL_NUMBER");
        aliases.put("homePhone", "HOME_PHONE");
        aliases.put("ldapUsername", "LDAP_USERNAME");
        aliases.put("maternityEndDate", "MATERNITY_END_DATE");
        aliases.put("maternityStartDate", "MATERNITY_START_DATE");
        aliases.put("businessArea1", "BUSINESS_AREA1");
        aliases.put("businessArea2", "BUSINESS_AREA2");
        aliases.put("businessArea3", "BUSINESS_AREA3");
        aliases.put("businessArea4", "BUSINESS_AREA4");
        aliases.put("logicallyDeleted", "LOGICALLY_DELETED");
        aliases.put("recordVersion", "RECORD_VERSION");
        aliases.put("createdUserId", "CREATED_USER_ID");
        aliases.put("createdDate", "CREATED_DATE");
        aliases.put("changedUserId", "CHANGED_USER_ID");
        aliases.put("changedDate", "CHANGED_DATE");
        aliases.put("employeeGroup", "EMPLOYEE_GROUP");
        aliases.put("employeeSubGroup", "EMPLOYEE_SUB_GROUP");
        aliases.put("nationalInsuranceNumber", "NATIONAL_INSURANCE_NUMBER");
        aliases.put("nationalRegistrationIdCard", "NATIONAL_REGISTRATION_ID_CARD");
        aliases.put("taxNumberOther", "TAX_NUMBER_OTHER");
        aliases.put("previousEntity", "PREVIOUS_ENTITY");
        aliases.put("entityChangeDate", "ENTITY_CHANGE_DATE");
        aliases.put("orgDepartmentChangeDate", "ORG_DEPARTMENT_CHANGE_DATE");
        aliases.put("orgUnitChangeDate", "ORG_UNIT_CHANGE_DATE");
        aliases.put("costCentreChangeDate", "COST_CENTRE_CHANGE_DATE");
        aliases.put("businessArea", "BUSINESS_AREA");
        aliases.put("previousBusinessArea", "PREVIOUS_BUSINESS_AREA");
        aliases.put("businessAreaChangeDate", "BUSINESS_AREA_CHANGE_DATE");
        aliases.put("personnelSubArea", "PERSONNEL_SUB_AREA");
        aliases.put("payrollArea", "PAYROLL_AREA");
        aliases.put("graduateStartDate", "GRADUATE_START_DATE");
        aliases.put("previousBusinessArea1", "PREVIOUS_BUSINESS_AREA1");
        aliases.put("businessArea1ChangeDate", "BUSINESS_AREA1_CHANGE_DATE");
        aliases.put("previousBusinessArea2", "PREVIOUS_BUSINESS_AREA2");
        aliases.put("businessArea2ChangeDate", "BUSINESS_AREA2_CHANGE_DATE");
        aliases.put("previousBusinessArea3", "PREVIOUS_BUSINESS_AREA3");
        aliases.put("businessArea3ChangeDate", "BUSINESS_AREA3_CHANGE_DATE");
        aliases.put("previousBusinessArea4", "PREVIOUS_BUSINESS_AREA4");
        aliases.put("businessArea4ChangeDate", "BUSINESS_AREA4_CHANGE_DATE");
        aliases.put("lineManagerId", "LINE_MANAGER_ID");
        aliases.put("personnelArea", "PERSONNEL_AREA");
        aliases.put("cdsStaffId", "CDS_STAFF_ID");
        aliases.put("lineManagerCdsStaffId", "LINE_MANAGER_CDS_STAFF_ID");
        aliases.put("localSupervisorCdsStaffId", "LOCAL_SUPERVISOR_CDS_STAFF_ID");
        aliases.put("personnelAreaDesc", "PERSONNEL_AREA_DESC");
        aliases.put("businessArea5", "BUSINESS_AREA5");
        aliases.put("businessArea5ChangeDate", "BUSINESS_AREA5_CHANGE_DATE");
        aliases.put("previousBusinessArea5", "PREVIOUS_BUSINESS_AREA5");
        aliases.put("subFunction", "SUB_FUNCTION");
        aliases.put("companyCode", "COMPANY_CODE");
        aliases.put("previousAddressLine1", "PREVIOUS_ADDRESS_LINE1");
        aliases.put("addressLine1ChangeDate", "ADDRESS_LINE1_CHANGE_DATE");
        aliases.put("previousAddressLine2", "PREVIOUS_ADDRESS_LINE2");
        aliases.put("addressLine2ChangeDate", "ADDRESS_LINE2_CHANGE_DATE");
        aliases.put("previousDateOfBirth", "PREVIOUS_DATE_OF_BIRTH");
        aliases.put("dateOfBirthChangeDate", "DATE_OF_BIRTH_CHANGE_DATE");
        aliases.put("previousEmailAddress", "PREVIOUS_EMAIL_ADDRESS");
        aliases.put("emailAddressChangeDate", "EMAIL_ADDRESS_CHANGE_DATE");
        aliases.put("previousFirstname", "PREVIOUS_FIRSTNAME");
        aliases.put("firstnameChangeDate", "FIRSTNAME_CHANGE_DATE");
        aliases.put("previousForenames", "PREVIOUS_FORENAMES");
        aliases.put("forenamesChangeDate", "FORENAMES_CHANGE_DATE");
        aliases.put("previousGender", "PREVIOUS_GENDER");
        aliases.put("genderChangeDate", "GENDER_CHANGE_DATE");
        aliases.put("previousJobTitle", "PREVIOUS_JOB_TITLE");
        aliases.put("jobTitleChangeDate", "JOB_TITLE_CHANGE_DATE");
        aliases.put("previousNationalityCode", "PREVIOUS_NATIONALITY_CODE");
        aliases.put("nationalityCodeChangeDate", "NATIONALITY_CODE_CHANGE_DATE");
        aliases.put("previousPostcode", "PREVIOUS_POSTCODE");
        aliases.put("postcodeChangeDate", "POSTCODE_CHANGE_DATE");
        aliases.put("previousHomePhone", "PREVIOUS_HOME_PHONE");
        aliases.put("homePhoneChangeDate", "HOME_PHONE_CHANGE_DATE");
        aliases.put("previousGtdEmailAddress", "PREVIOUS_GTD_EMAIL_ADDRESS");
        aliases.put("gtdEmailAddressChangeDate", "GTD_EMAIL_ADDRESS_CHANGE_DATE");
        aliases.put("previousJobRole", "PREVIOUS_JOB_ROLE");
        aliases.put("jobRoleChangeDate", "JOB_ROLE_CHANGE_DATE");
        aliases.put("surnameChangeDate", "SURNAME_CHANGE_DATE");
        aliases.put("previousTermReason", "PREVIOUS_TERM_REASON");
        aliases.put("termReasonChangeDate", "TERM_REASON_CHANGE_DATE");
        aliases.put("previousLastPaidDate", "PREVIOUS_LAST_PAID_DATE");
        aliases.put("lastPaidChangeDate", "LAST_PAID_CHANGE_DATE");
        aliases.put("previousLastWorkedDate", "PREVIOUS_LAST_WORKED_DATE");
        aliases.put("lastWorkedChangeDate", "LAST_WORKED_CHANGE_DATE");
        aliases.put("previousStartDate", "PREVIOUS_START_DATE");
        aliases.put("startChangeDate", "START_CHANGE_DATE");
        aliases.put("officeMobile", "OFFICE_MOBILE");
        aliases.put("operationalStatusInd", "OPERATIONAL_STATUS_IND");
        aliases.put("citizenCard", "CITIZEN_CARD");
        aliases.put("eveningTelNo", "EVENING_TEL_NO");
        aliases.put("idCard", "ID_CARD");
        aliases.put("panNo", "PAN_NO");
        aliases.put("nationalIdCardNo", "NATIONAL_ID_CARD_NO");
        aliases.put("labourCardNoId", "LABOUR_CARD_NO_ID");
        aliases.put("persMobCellTelNo", "PERS_MOB_CELL_TEL_NO");
        aliases.put("employmentPass", "EMPLOYMENT_PASS");
        aliases.put("singaporeBlue", "SINGAPORE_BLUE");
        aliases.put("passportNo", "PASSPORT_NO");
        aliases.put("hongkongIdNo", "HONGKONG_ID_NO");
        aliases.put("personalId", "PERSONAL_ID");
        aliases.put("uniqueNationalId", "UNIQUE_NATIONAL_ID");
        aliases.put("singaporePink", "SINGAPORE_PINK");
        aliases.put("visaWorkPermitRefTier2", "VISA_WORK_PERMIT_REF_TIER2");
        aliases.put("prevCorpTitle", "PREV_CORP_TITLE");
        aliases.put("corpTitleChangeDate", "CORP_TITLE_CHANGE_DATE");
        aliases.put("previousCompanyCode", "PREVIOUS_COMPANY_CODE");
        aliases.put("companyCodeChangeDate", "COMPANY_CODE_CHANGE_DATE");
        aliases.put("businessArea6", "BUSINESS_AREA6");
        aliases.put("previousBusinessArea6", "PREVIOUS_BUSINESS_AREA6");
        aliases.put("businessArea6ChangeDate", "BUSINESS_AREA6_CHANGE_DATE");
        aliases.put("businessArea7", "BUSINESS_AREA7");
        aliases.put("previousBusinessArea7", "PREVIOUS_BUSINESS_AREA7");
        aliases.put("businessArea7ChangeDate", "BUSINESS_AREA7_CHANGE_DATE");
        aliases.put("businessArea8", "BUSINESS_AREA8");
        aliases.put("previousBusinessArea8", "PREVIOUS_BUSINESS_AREA8");
        aliases.put("businessArea8ChangeDate", "BUSINESS_AREA8_CHANGE_DATE");
        aliases.put("businessArea9", "BUSINESS_AREA9");
        aliases.put("previousBusinessArea9", "PREVIOUS_BUSINESS_AREA9");
        aliases.put("businessArea9ChangeDate", "BUSINESS_AREA9_CHANGE_DATE");
        aliases.put("businessArea10", "BUSINESS_AREA10");
        aliases.put("previousBusinessArea10", "PREVIOUS_BUSINESS_AREA10");
        aliases.put("businessArea10ChangeDate", "BUSINESS_AREA10_CHANGE_DATE");
        aliases.put("prevLineManagerId", "PREV_LINE_MANAGER_ID");
        aliases.put("lineManagerIdChangeDate", "LINE_MANAGER_ID_CHANGE_DATE");
        aliases.put("prevFunction", "PREV_FUNCTION");
        aliases.put("functionChangeDate", "FUNCTION_CHANGE_DATE");
        aliases.put("prevSubFunction", "PREV_SUB_FUNCTION");
        aliases.put("subFunctionChangeDate", "SUB_FUNCTION_CHANGE_DATE");
        aliases.put("oprStatusIndChangeDate", "OPR_STATUS_IND_CHANGE_DATE");
        aliases.put("opNonOpStatusReason", "OP_NON_OP_STATUS_REASON");
        aliases.put("opNonOpStartDate", "OP_NON_OP_START_DATE");
        aliases.put("opNonOpEndDate", "OP_NON_OP_END_DATE");
        aliases.put("overallRecordChangedDate", "OVERALL_RECORD_CHANGED_DATE");

        qryEntity.setAliases(aliases);

        ArrayList<QueryIndex> indexes = new ArrayList<>();

        QueryIndex index = new QueryIndex();

        index.setName("BRID_UNIQUE");
        index.setIndexType(QueryIndexType.SORTED);

        LinkedHashMap<String, Boolean> indFlds = new LinkedHashMap<>();

        indFlds.put("brid", false);

        index.setFields(indFlds);
        indexes.add(index);

        qryEntity.setIndexes(indexes);
        qryEntities.add(qryEntity);

        ccfg.setQueryEntities(qryEntities);

        return ccfg;
    }

    /**
     * Create JDBC type for "jdbcTypeSapStaff".
     * 
     * @param cacheName Cache name.
     * @return Configured JDBC type.
     **/
    private static JdbcType jdbcTypeSapStaff(String cacheName) {
        JdbcType type = new JdbcType();

        type.setCacheName(cacheName);
        type.setKeyType(Long.class);
        type.setValueType("model.SapStaff");
        type.setDatabaseSchema("NIKHIL");
        type.setDatabaseTable("SAP_STAFF");

        type.setKeyFields(new JdbcTypeField(Types.BIGINT, "CDS_STAFF_ID", long.class, "cdsStaffId"));

        type.setValueFields(
            new JdbcTypeField(Types.BIGINT, "GLOBAL_STAFF_ID", long.class, "globalStaffId"),
            new JdbcTypeField(Types.BIGINT, "GLOBAL_STAFF_ID_OLD", Long.class, "globalStaffIdOld"),
            new JdbcTypeField(Types.VARCHAR, "WINDOWS_REALM", String.class, "windowsRealm"),
            new JdbcTypeField(Types.VARCHAR, "WINDOWS_USERNAME", String.class, "windowsUsername"),
            new JdbcTypeField(Types.VARCHAR, "STAFF_STATUS", String.class, "staffStatus"),
            new JdbcTypeField(Types.VARCHAR, "STAFF_TYPE", String.class, "staffType"),
            new JdbcTypeField(Types.VARCHAR, "CORPORATE_TITLE", String.class, "corporateTitle"),
            new JdbcTypeField(Types.VARCHAR, "TITLE", String.class, "title"),
            new JdbcTypeField(Types.VARCHAR, "FIRSTNAME", String.class, "firstname"),
            new JdbcTypeField(Types.VARCHAR, "SURNAME", String.class, "surname"),
            new JdbcTypeField(Types.VARCHAR, "FORENAMES", String.class, "forenames"),
            new JdbcTypeField(Types.CHAR, "GENDER", String.class, "gender"),
            new JdbcTypeField(Types.VARCHAR, "NATIONALITY_CODE", String.class, "nationalityCode"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_SURNAME", String.class, "previousSurname"),
            new JdbcTypeField(Types.VARCHAR, "ADDRESS_LINE1", String.class, "addressLine1"),
            new JdbcTypeField(Types.VARCHAR, "ADDRESS_LINE2", String.class, "addressLine2"),
            new JdbcTypeField(Types.TIMESTAMP, "ADDRESS_CHANGE_DATE", Timestamp.class, "addressChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "DISTRICT", String.class, "district"),
            new JdbcTypeField(Types.VARCHAR, "CITY", String.class, "city"),
            new JdbcTypeField(Types.VARCHAR, "COUNTY", String.class, "county"),
            new JdbcTypeField(Types.VARCHAR, "COUNTRY", String.class, "country"),
            new JdbcTypeField(Types.VARCHAR, "POSTCODE", String.class, "postcode"),
            new JdbcTypeField(Types.VARCHAR, "EMAIL_ADDRESS", String.class, "emailAddress"),
            new JdbcTypeField(Types.VARCHAR, "GTD_EMAIL_ADDRESS", String.class, "gtdEmailAddress"),
            new JdbcTypeField(Types.BIGINT, "STAFF_HIERARCHY", Long.class, "staffHierarchy"),
            new JdbcTypeField(Types.TIMESTAMP, "START_DATE", Timestamp.class, "startDate"),
            new JdbcTypeField(Types.TIMESTAMP, "END_DATE", Timestamp.class, "endDate"),
            new JdbcTypeField(Types.CHAR, "LEAVER", String.class, "leaver"),
            new JdbcTypeField(Types.TIMESTAMP, "LAST_WORKED_DATE", Timestamp.class, "lastWorkedDate"),
            new JdbcTypeField(Types.TIMESTAMP, "LAST_PAID_DATE", Timestamp.class, "lastPaidDate"),
            new JdbcTypeField(Types.TIMESTAMP, "ORIGINAL_START_DATE", Timestamp.class, "originalStartDate"),
            new JdbcTypeField(Types.VARCHAR, "TERMINATION_REASON", String.class, "terminationReason"),
            new JdbcTypeField(Types.CHAR, "OUT_OF_OFFICE", String.class, "outOfOffice"),
            new JdbcTypeField(Types.VARCHAR, "OUT_OF_OFFICE_REASON", String.class, "outOfOfficeReason"),
            new JdbcTypeField(Types.TIMESTAMP, "OUT_OF_OFFICE_RETURN_DATE", Timestamp.class, "outOfOfficeReturnDate"),
            new JdbcTypeField(Types.VARCHAR, "ORG_UNIT", String.class, "orgUnit"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_ORG_UNIT", String.class, "previousOrgUnit"),
            new JdbcTypeField(Types.VARCHAR, "ORG_DEPARTMENT", String.class, "orgDepartment"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_ORG_DEPARTMENT", String.class, "previousOrgDepartment"),
            new JdbcTypeField(Types.VARCHAR, "COST_CENTRE", String.class, "costCentre"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_COST_CENTRE", String.class, "previousCostCentre"),
            new JdbcTypeField(Types.NUMERIC, "LOCATION", BigDecimal.class, "location"),
            new JdbcTypeField(Types.NUMERIC, "PREV_LOCATION", BigDecimal.class, "prevLocation"),
            new JdbcTypeField(Types.TIMESTAMP, "LOCATION_CHANGE_DATE", Timestamp.class, "locationChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "FLOOR", String.class, "floor"),
            new JdbcTypeField(Types.VARCHAR, "DESK_NUMBER", String.class, "deskNumber"),
            new JdbcTypeField(Types.VARCHAR, "OFFICE_NORMAL_BUILDING_ID", String.class, "officeNormalBuildingId"),
            new JdbcTypeField(Types.CHAR, "ABSENT", String.class, "absent"),
            new JdbcTypeField(Types.VARCHAR, "ENTITY", String.class, "entity"),
            new JdbcTypeField(Types.VARCHAR, "SOCIAL_SECURITY_NUMBER", String.class, "socialSecurityNumber"),
            new JdbcTypeField(Types.TIMESTAMP, "DATE_OF_BIRTH", Timestamp.class, "dateOfBirth"),
            new JdbcTypeField(Types.VARCHAR, "JOB_TITLE", String.class, "jobTitle"),
            new JdbcTypeField(Types.VARCHAR, "JOB_ROLE", String.class, "jobRole"),
            new JdbcTypeField(Types.VARCHAR, "EXTENSION_NUMBER", String.class, "extensionNumber"),
            new JdbcTypeField(Types.VARCHAR, "GLOBAL_DIAL_NUMBER", String.class, "globalDialNumber"),
            new JdbcTypeField(Types.VARCHAR, "INTERNATIONAL_NUMBER", String.class, "internationalNumber"),
            new JdbcTypeField(Types.VARCHAR, "HOME_PHONE", String.class, "homePhone"),
            new JdbcTypeField(Types.VARCHAR, "LDAP_USERNAME", String.class, "ldapUsername"),
            new JdbcTypeField(Types.TIMESTAMP, "MATERNITY_END_DATE", Timestamp.class, "maternityEndDate"),
            new JdbcTypeField(Types.TIMESTAMP, "MATERNITY_START_DATE", Timestamp.class, "maternityStartDate"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA1", String.class, "businessArea1"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA2", String.class, "businessArea2"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA3", String.class, "businessArea3"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA4", String.class, "businessArea4"),
            new JdbcTypeField(Types.CHAR, "LOGICALLY_DELETED", String.class, "logicallyDeleted"),
            new JdbcTypeField(Types.NUMERIC, "RECORD_VERSION", BigDecimal.class, "recordVersion"),
            new JdbcTypeField(Types.VARCHAR, "CREATED_USER_ID", String.class, "createdUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CREATED_DATE", Timestamp.class, "createdDate"),
            new JdbcTypeField(Types.VARCHAR, "CHANGED_USER_ID", String.class, "changedUserId"),
            new JdbcTypeField(Types.TIMESTAMP, "CHANGED_DATE", Timestamp.class, "changedDate"),
            new JdbcTypeField(Types.VARCHAR, "EMPLOYEE_GROUP", String.class, "employeeGroup"),
            new JdbcTypeField(Types.VARCHAR, "EMPLOYEE_SUB_GROUP", String.class, "employeeSubGroup"),
            new JdbcTypeField(Types.VARCHAR, "NATIONAL_INSURANCE_NUMBER", String.class, "nationalInsuranceNumber"),
            new JdbcTypeField(Types.VARCHAR, "NATIONAL_REGISTRATION_ID_CARD", String.class, "nationalRegistrationIdCard"),
            new JdbcTypeField(Types.VARCHAR, "TAX_NUMBER_OTHER", String.class, "taxNumberOther"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_ENTITY", String.class, "previousEntity"),
            new JdbcTypeField(Types.TIMESTAMP, "ENTITY_CHANGE_DATE", Timestamp.class, "entityChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "ORG_DEPARTMENT_CHANGE_DATE", Timestamp.class, "orgDepartmentChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "ORG_UNIT_CHANGE_DATE", Timestamp.class, "orgUnitChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "COST_CENTRE_CHANGE_DATE", Timestamp.class, "costCentreChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA", String.class, "businessArea"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA", String.class, "previousBusinessArea"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA_CHANGE_DATE", Timestamp.class, "businessAreaChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PERSONNEL_SUB_AREA", String.class, "personnelSubArea"),
            new JdbcTypeField(Types.VARCHAR, "PAYROLL_AREA", String.class, "payrollArea"),
            new JdbcTypeField(Types.TIMESTAMP, "GRADUATE_START_DATE", Timestamp.class, "graduateStartDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA1", String.class, "previousBusinessArea1"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA1_CHANGE_DATE", Timestamp.class, "businessArea1ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA2", String.class, "previousBusinessArea2"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA2_CHANGE_DATE", Timestamp.class, "businessArea2ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA3", String.class, "previousBusinessArea3"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA3_CHANGE_DATE", Timestamp.class, "businessArea3ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA4", String.class, "previousBusinessArea4"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA4_CHANGE_DATE", Timestamp.class, "businessArea4ChangeDate"),
            new JdbcTypeField(Types.BIGINT, "LINE_MANAGER_ID", Long.class, "lineManagerId"),
            new JdbcTypeField(Types.VARCHAR, "PERSONNEL_AREA", String.class, "personnelArea"),
            new JdbcTypeField(Types.BIGINT, "LINE_MANAGER_CDS_STAFF_ID", Long.class, "lineManagerCdsStaffId"),
            new JdbcTypeField(Types.VARCHAR, "BRID", String.class, "brid"),
            new JdbcTypeField(Types.BIGINT, "LOCAL_SUPERVISOR_CDS_STAFF_ID", Long.class, "localSupervisorCdsStaffId"),
            new JdbcTypeField(Types.VARCHAR, "PERSONNEL_AREA_DESC", String.class, "personnelAreaDesc"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA5", String.class, "businessArea5"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA5_CHANGE_DATE", Timestamp.class, "businessArea5ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA5", String.class, "previousBusinessArea5"),
            new JdbcTypeField(Types.VARCHAR, "SUB_FUNCTION", String.class, "subFunction"),
            new JdbcTypeField(Types.VARCHAR, "FUNCTION", String.class, "function"),
            new JdbcTypeField(Types.VARCHAR, "COMPANY_CODE", String.class, "companyCode"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_ADDRESS_LINE1", String.class, "previousAddressLine1"),
            new JdbcTypeField(Types.TIMESTAMP, "ADDRESS_LINE1_CHANGE_DATE", Timestamp.class, "addressLine1ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_ADDRESS_LINE2", String.class, "previousAddressLine2"),
            new JdbcTypeField(Types.TIMESTAMP, "ADDRESS_LINE2_CHANGE_DATE", Timestamp.class, "addressLine2ChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "PREVIOUS_DATE_OF_BIRTH", Timestamp.class, "previousDateOfBirth"),
            new JdbcTypeField(Types.TIMESTAMP, "DATE_OF_BIRTH_CHANGE_DATE", Timestamp.class, "dateOfBirthChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_EMAIL_ADDRESS", String.class, "previousEmailAddress"),
            new JdbcTypeField(Types.TIMESTAMP, "EMAIL_ADDRESS_CHANGE_DATE", Timestamp.class, "emailAddressChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_FIRSTNAME", String.class, "previousFirstname"),
            new JdbcTypeField(Types.TIMESTAMP, "FIRSTNAME_CHANGE_DATE", Timestamp.class, "firstnameChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_FORENAMES", String.class, "previousForenames"),
            new JdbcTypeField(Types.TIMESTAMP, "FORENAMES_CHANGE_DATE", Timestamp.class, "forenamesChangeDate"),
            new JdbcTypeField(Types.CHAR, "PREVIOUS_GENDER", String.class, "previousGender"),
            new JdbcTypeField(Types.TIMESTAMP, "GENDER_CHANGE_DATE", Timestamp.class, "genderChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_JOB_TITLE", String.class, "previousJobTitle"),
            new JdbcTypeField(Types.TIMESTAMP, "JOB_TITLE_CHANGE_DATE", Timestamp.class, "jobTitleChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_NATIONALITY_CODE", String.class, "previousNationalityCode"),
            new JdbcTypeField(Types.TIMESTAMP, "NATIONALITY_CODE_CHANGE_DATE", Timestamp.class, "nationalityCodeChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_POSTCODE", String.class, "previousPostcode"),
            new JdbcTypeField(Types.TIMESTAMP, "POSTCODE_CHANGE_DATE", Timestamp.class, "postcodeChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_HOME_PHONE", String.class, "previousHomePhone"),
            new JdbcTypeField(Types.TIMESTAMP, "HOME_PHONE_CHANGE_DATE", Timestamp.class, "homePhoneChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_GTD_EMAIL_ADDRESS", String.class, "previousGtdEmailAddress"),
            new JdbcTypeField(Types.TIMESTAMP, "GTD_EMAIL_ADDRESS_CHANGE_DATE", Timestamp.class, "gtdEmailAddressChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_JOB_ROLE", String.class, "previousJobRole"),
            new JdbcTypeField(Types.TIMESTAMP, "JOB_ROLE_CHANGE_DATE", Timestamp.class, "jobRoleChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "SURNAME_CHANGE_DATE", Timestamp.class, "surnameChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_TERM_REASON", String.class, "previousTermReason"),
            new JdbcTypeField(Types.TIMESTAMP, "TERM_REASON_CHANGE_DATE", Timestamp.class, "termReasonChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "PREVIOUS_LAST_PAID_DATE", Timestamp.class, "previousLastPaidDate"),
            new JdbcTypeField(Types.TIMESTAMP, "LAST_PAID_CHANGE_DATE", Timestamp.class, "lastPaidChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "PREVIOUS_LAST_WORKED_DATE", Timestamp.class, "previousLastWorkedDate"),
            new JdbcTypeField(Types.TIMESTAMP, "LAST_WORKED_CHANGE_DATE", Timestamp.class, "lastWorkedChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "PREVIOUS_START_DATE", Timestamp.class, "previousStartDate"),
            new JdbcTypeField(Types.TIMESTAMP, "START_CHANGE_DATE", Timestamp.class, "startChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "OFFICE_MOBILE", String.class, "officeMobile"),
            new JdbcTypeField(Types.VARCHAR, "OPERATIONAL_STATUS_IND", String.class, "operationalStatusInd"),
            new JdbcTypeField(Types.VARCHAR, "CITIZEN_CARD", String.class, "citizenCard"),
            new JdbcTypeField(Types.VARCHAR, "EVENING_TEL_NO", String.class, "eveningTelNo"),
            new JdbcTypeField(Types.VARCHAR, "ID_CARD", String.class, "idCard"),
            new JdbcTypeField(Types.VARCHAR, "PAN_NO", String.class, "panNo"),
            new JdbcTypeField(Types.VARCHAR, "NATIONAL_ID_CARD_NO", String.class, "nationalIdCardNo"),
            new JdbcTypeField(Types.VARCHAR, "LABOUR_CARD_NO_ID", String.class, "labourCardNoId"),
            new JdbcTypeField(Types.VARCHAR, "PERS_MOB_CELL_TEL_NO", String.class, "persMobCellTelNo"),
            new JdbcTypeField(Types.VARCHAR, "EMPLOYMENT_PASS", String.class, "employmentPass"),
            new JdbcTypeField(Types.VARCHAR, "SINGAPORE_BLUE", String.class, "singaporeBlue"),
            new JdbcTypeField(Types.VARCHAR, "PASSPORT_NO", String.class, "passportNo"),
            new JdbcTypeField(Types.VARCHAR, "HONGKONG_ID_NO", String.class, "hongkongIdNo"),
            new JdbcTypeField(Types.VARCHAR, "PERSONAL_ID", String.class, "personalId"),
            new JdbcTypeField(Types.VARCHAR, "UNIQUE_NATIONAL_ID", String.class, "uniqueNationalId"),
            new JdbcTypeField(Types.VARCHAR, "SINGAPORE_PINK", String.class, "singaporePink"),
            new JdbcTypeField(Types.VARCHAR, "VISA_WORK_PERMIT_REF_TIER2", String.class, "visaWorkPermitRefTier2"),
            new JdbcTypeField(Types.VARCHAR, "PREV_CORP_TITLE", String.class, "prevCorpTitle"),
            new JdbcTypeField(Types.TIMESTAMP, "CORP_TITLE_CHANGE_DATE", Timestamp.class, "corpTitleChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_COMPANY_CODE", String.class, "previousCompanyCode"),
            new JdbcTypeField(Types.TIMESTAMP, "COMPANY_CODE_CHANGE_DATE", Timestamp.class, "companyCodeChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA6", String.class, "businessArea6"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA6", String.class, "previousBusinessArea6"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA6_CHANGE_DATE", Timestamp.class, "businessArea6ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA7", String.class, "businessArea7"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA7", String.class, "previousBusinessArea7"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA7_CHANGE_DATE", Timestamp.class, "businessArea7ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA8", String.class, "businessArea8"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA8", String.class, "previousBusinessArea8"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA8_CHANGE_DATE", Timestamp.class, "businessArea8ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA9", String.class, "businessArea9"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA9", String.class, "previousBusinessArea9"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA9_CHANGE_DATE", Timestamp.class, "businessArea9ChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "BUSINESS_AREA10", String.class, "businessArea10"),
            new JdbcTypeField(Types.VARCHAR, "PREVIOUS_BUSINESS_AREA10", String.class, "previousBusinessArea10"),
            new JdbcTypeField(Types.TIMESTAMP, "BUSINESS_AREA10_CHANGE_DATE", Timestamp.class, "businessArea10ChangeDate"),
            new JdbcTypeField(Types.BIGINT, "PREV_LINE_MANAGER_ID", Long.class, "prevLineManagerId"),
            new JdbcTypeField(Types.TIMESTAMP, "LINE_MANAGER_ID_CHANGE_DATE", Timestamp.class, "lineManagerIdChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREV_FUNCTION", String.class, "prevFunction"),
            new JdbcTypeField(Types.TIMESTAMP, "FUNCTION_CHANGE_DATE", Timestamp.class, "functionChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "PREV_SUB_FUNCTION", String.class, "prevSubFunction"),
            new JdbcTypeField(Types.TIMESTAMP, "SUB_FUNCTION_CHANGE_DATE", Timestamp.class, "subFunctionChangeDate"),
            new JdbcTypeField(Types.TIMESTAMP, "OPR_STATUS_IND_CHANGE_DATE", Timestamp.class, "oprStatusIndChangeDate"),
            new JdbcTypeField(Types.VARCHAR, "OP_NON_OP_STATUS_REASON", String.class, "opNonOpStatusReason"),
            new JdbcTypeField(Types.DATE, "OP_NON_OP_START_DATE", Date.class, "opNonOpStartDate"),
            new JdbcTypeField(Types.DATE, "OP_NON_OP_END_DATE", Date.class, "opNonOpEndDate"),
            new JdbcTypeField(Types.TIMESTAMP, "OVERALL_RECORD_CHANGED_DATE", Timestamp.class, "overallRecordChangedDate")
        );

        return type;
    }
}